version: '2'
services:
  webdav:
    container_name: webdav
    build: .
    ports:
      - "80:80"
    volumes:
      - "$HOME/docker/webdav:/media"
    environment:
      - USERNAME=webdav
      - PASSWORD=webdav
      - UID=1000
      - GID=1000
      - TZ=Europe/Madrid
      
      
      
